### ISSUE TITLE
Question: alternatives to PostFilter

### ISSUE THREAD

**Issue by imduffy15** [charybr/spring-data-rest-acl#1]
PostFilter seems like a neat solution to this problem.

However, the filtering is done on the application and this to me seems inefficient. If I understand correctly, our application fires off some database query the database returns several results, hibernate converts these into java objects then we sequentially loop through them removing whatever isn't required.

Is there any straight forward solution that enables us to extend the database query to apply the filtering and only return matching results?

I would be concerned that PostFilter gives poor performance on large datasets.

**Comment by charybr** [comment]
I agree. There is a discussion around this:
https://jira.spring.io/browse/SEC-2409

**Comment by imduffy15** [comment]
Thanks! Just realized I wrote on that JIRA a year ago haha.

Any idea if we can do something to automatically grab the username from the security context to add it into a modified spel named query? I the past what I've done is manually created a findByUsername and passed the username as a parameter but it meant writing my own controllers, I'd much rather let spring data rest handle all of that

**Comment by charybr** [comment]
there is a new feature in Spring Security 4.0.1, which might help to some extent (but not completely)
http://docs.spring.io/spring-security/site/docs/4.0.1.RELEASE/reference/htmlsingle/#data

**Comment by imduffy15** [comment]
That looks promising. Will make a fork and try it out.

Thanks.

**Comment by charybr** [comment]
Thanks very much! for taking time to discuss.

**Comment by imduffy15** [comment]
Hey @charybr another question for you just out of interest. Any reason why you didn't use spring boot for this?

**Comment by charybr** [comment]
I am yet to learn spring boot.
